language: java
install: true
script: bash ./travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - CI_DEPLOY_USERNAME=travis-mvn-deploy
  - secure: V9SYwxwMbGMbolDUNHDg3/jzdmyOuIX+RxA8gVLUIfAWgYOuo+OnCOnMwYhMgDjtHPlO9tLpf4gCNPpQopn5WZSi6r4xIpqZQJ4hduSPhCEzLRfTB6RVUNE4ARu4DMEMuiGlhJqFqJp+8bG44wJBM6YnVivLy4g9T2AEbv+2PbUa4csTtK9tMiYeRBEoVWo8dvxCafKy6/ZLQue3eGMii6byTAmGNdLw+O9uhxcOIembWRqFK32MDKbKuTEEmv1y5ku+xcJF+MIHRwWFm4+HtlqZY4JjsJFRN1Jx0WZbvRwY8Lha0nwLkn7JGyXHwo4myAFaEVXYLAJvy/nYCnduLgKs8oHkfRHs62/zX4mFWfTIxkVLIxy5S50GTQ5aJmpfChsaYvlIv4aBVQthYCAJ6lhCkPvUnkMi7wX2VeJSUsCWfv+6BsoIw53jsXbN/gE3QLCBcqfo5bZ43HqaN0sDR3lzCazta2Ae+rRzpwK4hXoy09JIh8FpuiKShOagLneh7WBkIn9K3+TRV8aXAnLr/P7/6cv9DK9ALxLfKpkWT04Fy/ryAtKSMxQeguw5mCE4m1YMreqGdMBRYDYmGdlTjs2TmMhhX22DuVAlO7mLKsWrf2Qxr/AhdBLDY1pK/TG3QKc3T6mfGxHxLTba5TtvFoyMZu1eozwAzCcgEIZQszM=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
