language: java
install: true
script: bash ./travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - CI_DEPLOY_USERNAME=travis-mvn-deploy
  - secure: qR1GI6dBZLMoQZ0I8hMlGWX06MO4D9gvuFA1q5FbK0Q4TUedkiE+WzwdpivoAZlYiEsChiI+zTtTMdYIp4G89s7AItHSpLQWMtj4ubqX2617QG8YgA7S5JxVKdoNNxrr8tO/I5XtZ0PEfe5qA9ZYwF0098qM4Luo56uR4B0yvrydKbqY1milEG8vlWP9kS3OAhZr49AZQfq4YrBslFHBxtfhVPcheQ/RWSQecpvzeu5v7QKYr7iVIvTobo5oXYixYpnt24XEey7iKQz/5XV9R6KBU0U42bb4ZF3bqjX73pEgepY4rhhh1mwtO+EZhVywmNLgAPclsZSmY0DZdLPfUOtQOK9b3I2wpr36cUFJALyyXTk0Wcfe0Jz7Tm6+RT2+pReoqcJjsMXHmSIWue8EljmZWqy/7oJ9PFzL2iW1MuhPqgibiCJXo0bPX+wVAElH7J43KIvL+smlwL2GWLe6UFqE9883YV6z1PSNzaIa5yWUy90nv1bMvk3h1A40STY2zyeJA9KH1otAoPACG3BiCYKHLNYTgfZAjyrcWvnuN6644vBxOrrhw0NvKX9jK6EpLSLzM3suARYDushuqzOSZwjlHQlc8A0gLi86stQnETcmK7m6CUwTB1kUHf/XcHVJGxF85mexzjzfrhgRjs/2wArRcLa4tsydCMuaiWTXQiE=
notifications:
  email: false
  slack:
    rooms:
    - secure: uaQTZgu2e6UEbg4EssdPgt2xnkCRQ5533bFfpJWlJjFpOFM0BNAbdTx8azK1I466i9Y/DuVjMnCy1iWFbrh6F6NAAw2FMu3BDIAyvf2nY+p7Pim2VsM4/zXBTdIc2ChdV0lXlzW0kYiZ67fb3FxHcedYY2WFLBWuvIPhsJzzFPmXXmDuHPyBye1fHVF5XJCwqjn7pEKniTTEwRtWAUXU9URUyemY/rPyV/0+lm79518hOSY9kzoaoPsk1Q+m9pHtuM0oBYIdgo0IRlAO/7evWNGGQ5Tdo/GzBqegere7Wf/QjUqVVYE9iGZRRErH0Mi0fvRdni5NJ0HotC2tte3KxXje/5TaivMWykQBu/h2CnpKG2GkOOUkTaCM0JA3/VBV92ZlZ3cL8wHSrzwVeUAOCBiLhDFPekgXUhRZoD6b6gILw2dwE5u/ObEq+l5Lh6uk0rKUBxPZl8aEX/+9sA3fOgDpwy2DATiNquO2lfrw25wERQG0YIwTC5WOgSOvPC+eARF15GVLaMHrnV0i7jggqVYm/OtI1tCspk/k0dxX/U4Q7FRToB6D6Cu8p6ssk9FgGcjKkqHOoWM8gFuXgjeIo4/VZtQGlNfi9kDUwUpVuT8p1kId3jwFdy6mMWxjTtRtd9To61tp0PUbvjh60JAOV1BVqTVvw+3e6bGzwB7X4d8=
    - secure: MWy0igHw1KcA95yS38hb4x22ix97se6d6XzJntZ/RNRzW+fgK4JpQE6iiQK18lSzNt851warw/AIBrLf9uX1lE7MQMCnLlxLaaaF+6FOjQn7ay2TBEkxcrLFmP6PMLXYPUU0WuxuoqSleWpcCbzvMnBnlgSeCIHoP4Z6PKO/GGRbcNBSkNY+yYNZ0aRipirmXKI87LiJi/gbC14vlZaTshCU4zxR8M+GZwyYz0HUWkXkDRDfol521Sie3IVxdNplW0Z/0I+2288Huy/6w8KJtCWNeZpKelr2QA9q5dM/3Y1/ZcX1fPE3WqvmZoJ9P7yWOd6fHEFg3aSeXs14exPG9FK+d8DJyHtB27XCfVt3h5A+lEghfErEUidP29BlR+VXHTJnMYQu02eYQGWRf/cEMm+4Gi0Uzjmi3BVxL5XT005FoeHYVwOIJWyzwwfm5R6SR+qtcvMAw0yimHf0pEsB1Urw422PX1cIgdR3JRcdNwb0eQb8mc2eXf0+ADXmTUVZecuSty9LXeUdi3s33DF5Sq7fyTis4Ft0hD3z5ZRjzHg3ha7cJAUssB8wJUK1rvn5q5qGDmiTnGNBt2eISM9Q7954JrWzdUSGgBEI/n/v3L6jGbyKD6RpJx+GdJpYKPuinAgr/LM/8VtRfOyldNqJd/4mx7Loklw5jvGZOvQWM+4=
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: EHxTRpdxaSOjBT+1Paw0ts2Qb8F2lv47NpfqKraBFM5HjbvXHwAglglz9dS6wN0akyl22VohHBc6quhuog5/Q3jahIcivmMlDgJJjbid2ZE25O/utCrHktEDmhD9lCs9Wz2Q1+ORBxONmL3n4U07AnbZbU6/HAJfjR8EIchuFNo7OmiUbkieHqVutO/xhtceId5RSSAS3VY4RHwjyPMlzoMYSKIK8DOXEuI0OpHoQ/YaGZyx3O/ZGbnqZ281/hFvaCWJEf6kf1R464JdtGklPni4OzToyufJvIbrdrYmWEvcK2QZjiKivBWt4pd8VDY163kN99k+xs61AFGMxr1eQ5HK4FtOG5lcZD1gw/MhKJvTbHlWp3wCsIX43FqP6SH5Ez38vV98fk498ggYb54TVi/eT3jtHFqQaxyKWLCF3XhcCvqL24ONsfDyIt4aYb8tUduPWpv7Qlcyx8ilN95edsKnb9wqiqicsnuwd/wPOygL0E3wIZOpF2MCSW5KrVs4UOagyKmCy4KvKJGJ+P1kOT+4WHecOWo6wC/Bzf16VTXIhzUf7/BUGPU8c4z5k81R4C42BcKtDLhOv53wnw1i0PE3IUw+Y4U1aMKkSUwgThTG+DqjCqrQ1QW+bgPSj5n5Df7BB9ssmB3/F5JSzNRn89o54OjK3NXK8XIpdxfezBw=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
